### Monte-Carlo sampling to compare no. of edges in subgraphs generated 
### by random genes, compare against subgraph generated by GOI.

install.packages("igraph")
library("igraph")

p = 0.05
G=suppressWarnings(read.graph("synaptome.graphml",format="graphml"))
G=as.undirected(G,mode="collapse")
G_genes=V(G)

G_metric=function(G) gsize(G) 
GOI=c("AMPH", "AP2B1", "AP2M1", "AP2S1", "DNM1", "DNM2", "EPN1", "RAB5C")
G_GOI_subgraph=induced.subgraph(G,GOI)

# Monte-Carlo sampling of random subgraphs
MC_rounds = 10000
MC_samples = c()
message( sprintf("Perform %i rounds of mc sampling...", MC_rounds ) )
MC_progressbar=txtProgressBar(min=0, max=MC_rounds, style=3)

for (r in 1:MC_rounds)
{ G_subgraph= induced.subgraph(G,sample(G_genes,length(GOI),replace=F))
  MC_samples[r]= G_metric(G_subgraph)
  setTxtProgressBar(MC_progressbar,r)
}
close(MC_progressbar)
message("")

MC_quantile= quantile(MC_samples,1-p)
m_G_GOI_subgraph= G_metric(G_GOI_subgraph)
if(m_G_GOI_subgraph>MC_quantile)
  {message(sprintf("Induced subgraph is more connected (%i>%i)",m_G_GOI_subgraph,MC_quantile))
} else {
  message(sprintf("Induced subgraph is more connected (%i<%i)",m_G_GOI_subgraph,MC_quantile))
}
ecdf(MC_samples)(m_G_GOI_subgraph)
1-(ecdf(MC_samples)(m_G_GOI_subgraph))

pValue= 1
d_pValue= 0.0001
while(pValue>0)
{ pValue_=max(pValue-d_pValue,0)
  if(m_G_GOI_subgraph>quantile(MC_samples,1-pValue_))
  {pValue= pValue_;
  } else{
    break;
  }
}
message(sprintf("P-value:%f",pValue))
